name: pebblecounts
channels:
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.6
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - cloudpickle=0.6.1
  - curl=7.63.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask-core=1.0.0
  - decorator=4.3.0
  - expat=2.2.5
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.3.3
  - geos=3.7.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - imageio=2.4.1
  - intel-openmp=2019.1
  - jpeg=9b
  - kealib=1.4.7
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.63.0
  - libgdal=2.3.3
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.36
  - libpq=11.1
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.9
  - matplotlib=3.0.2
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - networkx=2.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - opencv=3.3.1
  - openssl=1.1.1a
  - pcre=8.42
  - pillow=5.4.1
  - pip=18.1
  - proj4=5.2.0
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.7.5
  - pytz=2018.9
  - pywavelets=1.0.1
  - qt=5.9.7
  - scikit-image=0.14.1
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - setuptools=40.6.3
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1.1
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wheel=0.32.3
  - wincertstore=0.2
  - xerces-c=3.2.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - dask==1.0.0
prefix: C:\Miniconda3\envs\pebblecounts

